//! Format-stability proof (dogfooding item 1): buckets written by the
//! PUBLISHED walrust 0.7.0 artifacts must restore row-exact forever.
//!
//! `tests/fixtures/format-stability/` holds two frozen buckets generated by
//! `generate.sh` from the real crates.io 0.7.0 artifacts (see that script's
//! header): `cli-v0.7.0` (published CLI binary, leveled + pruned,
//! LTX L0 ⟷ HADBP levels seam) and `owned-v0.7.0` (registry walrust-core,
//! owned one-object-per-seq layout + levels). Each test uploads its fixture's
//! objects to a unique scratch prefix on the live S3 endpoint and drives the
//! SAME restore path a real user uses — the CLI binary for the CLI fixture,
//! the library `Replicator::restore()` / `sync::restore()` for the owned one
//! — asserting restore-to-latest and PITR are row-exact against the
//! MANIFEST.json checksums and that `PRAGMA integrity_check` passes.
//!
//! Beyond the two recorded restore points, each test also proves the parts of
//! the frozen bucket those restores never touch: every HADBP payload (merged
//! `levels/` objects in both fixtures, every `.hadbp` object in the owned one)
//! must decode with the current decoder (content checksums verified); the CLI
//! fixture must pass `walrust verify` (which downloads and checksum-verifies
//! every real-LTX object and runs the prune-/level-aware gap logic); and the
//! owned fixture is PITR-restored through each 0.7.0-written L1 merged object
//! (snapshot base + apply-plan chain linkage), with the result required to be
//! a strict prefix of the manifest-anchored latest rows.
//!
//! Skip policy (never weaken): these tests skip ONLY when no S3
//! endpoint/credentials are configured, exactly like every other S3-gated
//! test in this file's siblings. When S3 IS configured, a missing or corrupt
//! fixture file is a loud FAILURE — never a skip, never a pass.

use anyhow::{Context, Result};
use hadb_storage::StorageBackend;
use rusqlite::Connection;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

fn test_bucket() -> String {
    std::env::var("TIERED_TEST_BUCKET").unwrap_or_else(|_| "walrust-test-rr-2026".to_string())
}

fn test_endpoint() -> Option<String> {
    std::env::var("AWS_ENDPOINT_URL_S3")
        .or_else(|_| std::env::var("AWS_ENDPOINT_URL"))
        .ok()
}

/// S3-backed tests run only when S3 credentials/an endpoint are configured
/// (same gating as tests/production_e2e.rs — skip ONLY on missing S3 env).
fn s3_test_enabled() -> bool {
    std::env::var("AWS_ENDPOINT_URL_S3").is_ok()
        || std::env::var("AWS_ENDPOINT_URL").is_ok()
        || std::env::var("AWS_ACCESS_KEY_ID").is_ok()
}

macro_rules! require_s3 {
    ($name:literal) => {
        if !s3_test_enabled() {
            eprintln!(concat!(
                "SKIP ",
                $name,
                ": no S3 endpoint/credentials configured (set AWS_ACCESS_KEY_ID or AWS_ENDPOINT_URL_S3)"
            ));
            return Ok(());
        }
    };
}

fn unique_scratch_prefix(fixture: &str) -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("e2e/format-stability/{fixture}-{nanos}")
}

// ── Fixture manifest ────────────────────────────────────────────────────────

#[derive(serde::Deserialize)]
struct Manifest {
    db_name: String,
    latest: RestorePoint,
    pitr: PitrPoint,
    objects: Vec<ObjectEntry>,
}

#[derive(serde::Deserialize)]
struct RestorePoint {
    row_count: u64,
    rows_sha256: String,
}

#[derive(serde::Deserialize)]
struct PitrPoint {
    txid: u64,
    row_count: u64,
    rows_sha256: String,
}

#[derive(serde::Deserialize)]
struct ObjectEntry {
    key: String,
    size: u64,
}

fn fixture_dir(fixture: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/format-stability")
        .join(fixture)
}

/// Load a fixture's manifest. With S3 configured, ANY problem here (missing
/// dir, missing MANIFEST.json, unparseable JSON, empty object list, or a
/// manifest that drifted from the files actually on disk) is a loud test
/// failure — a broken fixture must never look like a pass or a skip.
fn load_manifest(fixture: &str) -> Result<Manifest> {
    let dir = fixture_dir(fixture);
    let manifest_path = dir.join("MANIFEST.json");
    let raw = std::fs::read(&manifest_path).with_context(|| {
        format!(
            "fixture {fixture} is missing or unreadable at {} — \
             regenerate with tests/fixtures/format-stability/generate.sh; \
             this is a FAILURE, not a skip",
            manifest_path.display()
        )
    })?;
    let manifest: Manifest = serde_json::from_slice(&raw)
        .with_context(|| format!("fixture {fixture}: MANIFEST.json is corrupt"))?;
    anyhow::ensure!(
        !manifest.objects.is_empty(),
        "fixture {fixture}: MANIFEST.json lists zero objects"
    );
    anyhow::ensure!(
        manifest.latest.row_count > 0 && manifest.pitr.row_count > 0,
        "fixture {fixture}: manifest row counts must be non-zero"
    );

    // Manifest ↔ disk set equality. A missing file is caught at upload time;
    // this catches the other direction — files on disk the manifest does NOT
    // list (a silently-shrunk manifest would silently shrink the proof).
    let objects_dir = dir.join("objects");
    let mut on_disk = std::collections::BTreeSet::new();
    let mut stack = vec![objects_dir.clone()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d)
            .with_context(|| format!("fixture {fixture}: cannot list {}", d.display()))?
        {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                let rel = path
                    .strip_prefix(&objects_dir)
                    .expect("walked path is under objects_dir")
                    .to_string_lossy()
                    .replace(std::path::MAIN_SEPARATOR, "/");
                on_disk.insert(rel);
            }
        }
    }
    let in_manifest: std::collections::BTreeSet<String> =
        manifest.objects.iter().map(|o| o.key.clone()).collect();
    let extra: Vec<&String> = on_disk.difference(&in_manifest).collect();
    anyhow::ensure!(
        extra.is_empty(),
        "fixture {fixture}: objects on disk not listed in MANIFEST.json (manifest drift): {extra:?}"
    );
    Ok(manifest)
}

// ── HADBP decode guard (format stability of restore-unreachable objects) ───
//
// The end-to-end restores below only decode objects on a restore path, and a
// pruned/compacted 0.7.0 bucket legitimately carries objects NO restore can
// reach (e.g. the cli fixture's L2 ranges sit entirely under the newest
// snapshot with their fine history pruned; the owned fixture's L2 predates
// the first snapshot). Their bytes are still frozen 0.7.0 output, so decode
// every HADBP payload — merged `levels/` objects in both fixtures, and every
// `.hadbp` snapshot/delta in the owned fixture — with the CURRENT decoder.
// `decode_sqlite_changeset` verifies the embedded content checksum, so a
// format break or a single flipped byte fails loudly. (The cli fixture's
// `0000/` + generation objects are real-LTX, not HADBP; their content is
// covered end-to-end by the restores and by `walrust verify` below.)
fn assert_hadbp_objects_decode(fixture: &str, manifest: &Manifest) -> Result<()> {
    let objects_dir = fixture_dir(fixture).join("objects");
    let mut decoded = 0usize;
    for entry in &manifest.objects {
        let is_merged_level = entry.key.contains("/levels/");
        let is_owned_hadbp = entry.key.ends_with(".hadbp");
        if !is_merged_level && !is_owned_hadbp {
            continue;
        }
        let data = std::fs::read(objects_dir.join(&entry.key))
            .with_context(|| format!("fixture {fixture}: cannot read object {}", entry.key))?;
        walrust::walrust_core::ltx::decode_sqlite_changeset(&data).with_context(|| {
            format!(
                "fixture {fixture}: object {} was written by walrust 0.7.0 but no longer \
                 decodes with the current HADBP decoder — format stability is broken",
                entry.key
            )
        })?;
        decoded += 1;
    }
    anyhow::ensure!(
        decoded > 0,
        "fixture {fixture}: no HADBP objects found to decode — the fixture shape changed \
         and this guard went vacuous"
    );
    Ok(())
}

/// Upload every fixture object to `{scratch_prefix}/{key}`. A missing object
/// file or a size that disagrees with the manifest fails loudly.
async fn upload_fixture(
    storage: &Arc<dyn StorageBackend>,
    fixture: &str,
    manifest: &Manifest,
    scratch_prefix: &str,
) -> Result<()> {
    let objects_dir = fixture_dir(fixture).join("objects");
    for entry in &manifest.objects {
        let path = objects_dir.join(&entry.key);
        let data = std::fs::read(&path).with_context(|| {
            format!(
                "fixture {fixture}: object {} missing at {} — \
                 the checked-in fixture is broken; this is a FAILURE, not a skip",
                entry.key,
                path.display()
            )
        })?;
        anyhow::ensure!(
            data.len() as u64 == entry.size,
            "fixture {fixture}: object {} is {} bytes on disk but MANIFEST.json says {}",
            entry.key,
            data.len(),
            entry.size
        );
        let key = format!("{scratch_prefix}/{}", entry.key);
        storage
            .put(&key, &data)
            .await
            .with_context(|| format!("upload fixture object {key}"))?;
    }
    Ok(())
}

/// Best-effort scratch cleanup: delete everything under the prefix.
async fn delete_scratch(storage: &Arc<dyn StorageBackend>, scratch_prefix: &str) {
    let prefix = format!("{scratch_prefix}/");
    if let Ok(keys) = storage.list(&prefix, None).await {
        for key in keys {
            let _ = storage.delete(&key).await;
        }
    }
}

// ── Row-content checksum (canonical; matches generate.sh) ──────────────────
//
// SHA-256 over the concatenation of "{id}|{value}\n" for
// `SELECT id, value FROM items ORDER BY id`.
fn read_rows(path: &Path) -> Result<Vec<(i64, String)>> {
    let conn = Connection::open(path)?;
    let mut stmt = conn.prepare("SELECT id, value FROM items ORDER BY id")?;
    let rows = stmt.query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, String>(1)?)))?;
    Ok(rows.collect::<std::result::Result<Vec<_>, _>>()?)
}

fn rows_sha(path: &Path) -> Result<(u64, String)> {
    let rows = read_rows(path)?;
    let mut hasher = Sha256::new();
    for (id, value) in &rows {
        hasher.update(format!("{id}|{value}\n"));
    }
    Ok((rows.len() as u64, format!("{:x}", hasher.finalize())))
}

fn assert_integrity_ok(path: &Path) -> Result<()> {
    let conn = Connection::open(path)?;
    let integrity: String = conn.query_row("PRAGMA integrity_check", [], |row| row.get(0))?;
    anyhow::ensure!(integrity == "ok", "integrity_check failed: {integrity}");
    Ok(())
}

fn assert_restored_matches(
    label: &str,
    restored: &Path,
    expected_rows: u64,
    expected_sha: &str,
) -> Result<()> {
    assert_integrity_ok(restored).with_context(|| format!("{label}: integrity_check"))?;
    let (rows, sha) = rows_sha(restored)?;
    anyhow::ensure!(
        rows == expected_rows,
        "{label}: row count mismatch — expected {expected_rows}, restored {rows}"
    );
    anyhow::ensure!(
        sha == expected_sha,
        "{label}: row-content checksum mismatch — expected {expected_sha}, restored {sha}"
    );
    Ok(())
}

// ── CLI restore path (the same binary/path a real CLI user runs) ───────────

fn run_cli_restore(
    name: &str,
    bucket_arg: &str,
    endpoint: Option<&str>,
    restored_path: &Path,
    point_in_time: Option<u64>,
) -> Result<()> {
    let mut restore = Command::new(env!("CARGO_BIN_EXE_walrust"));
    restore
        .arg("restore")
        .arg(name)
        .arg("--output")
        .arg(restored_path)
        .arg("--bucket")
        .arg(bucket_arg);
    if let Some(pit) = point_in_time {
        restore.arg("--point-in-time").arg(pit.to_string());
    }
    if let Some(endpoint) = endpoint {
        restore.arg("--endpoint").arg(endpoint);
    }
    let output = restore.output().context("run walrust restore")?;
    anyhow::ensure!(
        output.status.success(),
        "walrust restore failed (pit={point_in_time:?})\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    Ok(())
}

// ── Mid-level PITR targets (owned fixture) ──────────────────────────────────
//
// Restore-to-latest plans forward from the NEWEST snapshot, so it never
// decodes a merged `levels/` object that sits below it. To prove the leveled
// restore planner (`gather_candidates`/`plan_restore`/`apply_plan`) decodes
// GENUINE 0.7.0-written merged objects — snapshot base + L1 chain-checksum
// linkage across the seam — derive PITR targets from the manifest: for every
// L1 range `[min, max]` with a snapshot exactly at `min-1`, PITR to `max`
// must restore through that snapshot and that L1 object.
fn owned_snapshot_seqs(manifest: &Manifest) -> Vec<u64> {
    let snap_dir = format!("{}/0001/", manifest.db_name);
    manifest
        .objects
        .iter()
        .filter_map(|o| {
            let stem = o.key.strip_prefix(&snap_dir)?.strip_suffix(".hadbp")?;
            u64::from_str_radix(stem, 16).ok()
        })
        .collect()
}

fn owned_l1_ranges(manifest: &Manifest) -> Vec<(u64, u64)> {
    let l1_dir = format!("{}/levels/L1/", manifest.db_name);
    manifest
        .objects
        .iter()
        .filter_map(|o| {
            let stem = o.key.strip_prefix(&l1_dir)?.strip_suffix(".hadbp")?;
            let (min, max) = stem.split_once('-')?;
            Some((
                u64::from_str_radix(min, 16).ok()?,
                u64::from_str_radix(max, 16).ok()?,
            ))
        })
        .collect()
}

// ── The proofs ──────────────────────────────────────────────────────────────

/// A bucket written by the PUBLISHED walrust 0.7.0 CLI binary (leveled
/// compaction + a prune boundary, LTX L0 ⟷ HADBP levels seam) restores
/// row-exact through the current CLI restore path: latest + PITR + integrity.
#[tokio::test]
async fn format_stability_cli_v0_7_0_bucket_restores_row_exact() -> Result<()> {
    require_s3!("format_stability_cli_v0_7_0_bucket_restores_row_exact");
    let fixture = "cli-v0.7.0";
    let manifest = load_manifest(fixture)?;
    assert_hadbp_objects_decode(fixture, &manifest)?;
    let scratch = unique_scratch_prefix("cli");
    let bucket = test_bucket();
    let endpoint = test_endpoint();
    let storage = walrust::s3_backend_from_env(bucket.clone(), endpoint.as_deref()).await?;

    upload_fixture(&storage, fixture, &manifest, &scratch).await?;

    let result = (|| -> Result<()> {
        let temp = tempfile::TempDir::new()?;
        let bucket_arg = format!("{bucket}/{scratch}");

        // Restore-to-latest via the real CLI path.
        let latest_out = temp.path().join("latest.db");
        run_cli_restore(
            &manifest.db_name,
            &bucket_arg,
            endpoint.as_deref(),
            &latest_out,
            None,
        )?;
        assert_restored_matches(
            "cli-v0.7.0 restore-to-latest",
            &latest_out,
            manifest.latest.row_count,
            &manifest.latest.rows_sha256,
        )?;

        // PITR to the recorded mid-history TXID via the real CLI path.
        let pitr_out = temp.path().join("pitr.db");
        run_cli_restore(
            &manifest.db_name,
            &bucket_arg,
            endpoint.as_deref(),
            &pitr_out,
            Some(manifest.pitr.txid),
        )?;
        assert_restored_matches(
            "cli-v0.7.0 PITR",
            &pitr_out,
            manifest.pitr.row_count,
            &manifest.pitr.rows_sha256,
        )?;

        // `walrust verify` (same binary/path a real user runs) must exit 0 on
        // the 0.7.0 bucket. This downloads and checksum-verifies EVERY real-LTX
        // object — including L0 objects the two restores above never touch —
        // and exercises the level-/prune-aware gap logic against a genuine
        // pruned 0.7.0 layout.
        let mut verify = Command::new(env!("CARGO_BIN_EXE_walrust"));
        verify
            .arg("verify")
            .arg(&manifest.db_name)
            .arg("--bucket")
            .arg(&bucket_arg);
        if let Some(endpoint) = endpoint.as_deref() {
            verify.arg("--endpoint").arg(endpoint);
        }
        let output = verify.output().context("run walrust verify")?;
        anyhow::ensure!(
            output.status.success(),
            "walrust verify failed on the cli-v0.7.0 fixture bucket\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        Ok(())
    })();

    delete_scratch(&storage, &scratch).await;
    result
}

/// A published 0.7 CLI LTX stream remains the immutable historical prefix
/// when default watch crosses to its versioned native HADBP snapshot boundary.
#[tokio::test]
async fn format_stability_cli_v0_7_0_migrates_to_native_hadbp_boundary() -> Result<()> {
    require_s3!("format_stability_cli_v0_7_0_migrates_to_native_hadbp_boundary");
    let fixture = "cli-v0.7.0";
    let manifest = load_manifest(fixture)?;
    let scratch = unique_scratch_prefix("cli-native-migration");
    let bucket = test_bucket();
    let endpoint = test_endpoint();
    let storage = walrust::s3_backend_from_env(bucket.clone(), endpoint.as_deref()).await?;
    upload_fixture(&storage, fixture, &manifest, &scratch).await?;

    let result = async {
        let temp = tempfile::TempDir::new()?;
        let bucket_arg = format!("{bucket}/{scratch}");
        let db = temp.path().join(format!("{}.db", manifest.db_name));
        let watch_log_path = temp.path().join("migration-watch.log");
        run_cli_restore(
            &manifest.db_name,
            &bucket_arg,
            endpoint.as_deref(),
            &db,
            None,
        )?;
        assert_restored_matches(
            "legacy head before native migration",
            &db,
            manifest.latest.row_count,
            &manifest.latest.rows_sha256,
        )?;

        let watch_log = std::fs::File::create(&watch_log_path)?;
        let mut watch = Command::new(env!("CARGO_BIN_EXE_walrust"));
        watch
            .env(
                "RUST_LOG",
                "walrust_core::shadow=debug,walrust::sync::watch_shadow=debug,walrust_core::native_publish=info",
            )
            .arg("watch")
            .arg(&db)
            .arg("--bucket")
            .arg(&bucket_arg)
            .arg("--snapshot-interval")
            .arg("3600")
            .arg("--wal-sync-interval")
            .arg("1")
            .arg("--checkpoint-interval")
            .arg("1")
            .arg("--min-checkpoint-pages")
            .arg("1")
            .arg("--wal-truncate-threshold")
            .arg("100000")
            .arg("--no-metrics")
            .stdout(watch_log.try_clone()?)
            .stderr(watch_log);
        if let Some(endpoint) = endpoint.as_deref() {
            watch.arg("--endpoint").arg(endpoint);
        }
        let mut child = watch.spawn().context("start native migration watcher")?;
        let migration_result = async {
            let startup_deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
            loop {
                if let Some(status) = child.try_wait()? {
                    anyhow::bail!("native migration watcher exited during startup: {status}");
                }
                let descriptor_key =
                    format!("{scratch}/{}/native/v1/stream.json", manifest.db_name);
                if let Some(bytes) = storage.get(&descriptor_key).await? {
                    let descriptor: walrust::walrust_core::native_publish::StreamDescriptor =
                        serde_json::from_slice(&bytes)?;
                    let published_base = format!(
                        "{scratch}/{}/native/v1/lineages/{}/published/{:016x}.json",
                        manifest.db_name, descriptor.lineage_id, descriptor.first_native_seq
                    );
                    if storage.get(&published_base).await?.is_some() {
                        break;
                    }
                }
                anyhow::ensure!(
                    std::time::Instant::now() < startup_deadline,
                    "timed out waiting for the first published native migration snapshot"
                );
                tokio::time::sleep(std::time::Duration::from_millis(100)).await;
            }

            let writer = Connection::open(&db)?;
            writer.execute_batch("PRAGMA journal_mode=WAL; PRAGMA wal_autocheckpoint=0;")?;
            writer.execute(
                "INSERT INTO items(value) VALUES ('post-native-migration')",
                [],
            )?;
            let journal_mode: String = writer.query_row("PRAGMA journal_mode", [], |row| row.get(0))?;
            let live_rows: u64 = writer.query_row("SELECT count(*) FROM items", [], |row| row.get(0))?;
            let wal_path = db.with_extension("db-wal");
            let wal_before_close = std::fs::metadata(&wal_path).map(|metadata| metadata.len()).unwrap_or(0);
            anyhow::ensure!(
                journal_mode.eq_ignore_ascii_case("wal")
                    && live_rows == manifest.latest.row_count + 1
                    && wal_before_close > 0,
                "post-migration commit was not live in WAL mode: mode={journal_mode} rows={live_rows} wal_bytes={wal_before_close}"
            );
            drop(writer);

            let latest = temp.path().join("native-latest.db");
            let publish_deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
            let mut last_restore_error: String;
            loop {
                let restored = run_cli_restore(
                    &manifest.db_name,
                    &bucket_arg,
                    endpoint.as_deref(),
                    &latest,
                    None,
                )
                .and_then(|_| read_rows(&latest));
                match restored {
                    Ok(rows) => {
                        last_restore_error = format!(
                            "restore contained {} rows; last={:?}",
                            rows.len(),
                            rows.last()
                        );
                        if rows.len() as u64 == manifest.latest.row_count + 1
                            && rows.last().map(|(_, value)| value.as_str())
                                == Some("post-native-migration")
                        {
                            assert_integrity_ok(&latest)?;
                            break;
                        }
                    }
                    Err(error) => last_restore_error = format!("{error:#}"),
                }
                if let Some(status) = child.try_wait()? {
                    anyhow::bail!("native migration watcher exited before publish: {status}");
                }
                anyhow::ensure!(
                    std::time::Instant::now() < publish_deadline,
                    "timed out waiting for native migration latest restore; last restore: {}; watcher:\n{}",
                    last_restore_error,
                    std::fs::read_to_string(&watch_log_path).unwrap_or_default()
                );
                tokio::time::sleep(std::time::Duration::from_millis(200)).await;
            }

            let old_pitr = temp.path().join("legacy-pitr-after-migration.db");
            run_cli_restore(
                &manifest.db_name,
                &bucket_arg,
                endpoint.as_deref(),
                &old_pitr,
                Some(manifest.pitr.txid),
            )?;
            assert_restored_matches(
                "legacy PITR after native migration",
                &old_pitr,
                manifest.pitr.row_count,
                &manifest.pitr.rows_sha256,
            )?;

            let keys = storage
                .list(&format!("{scratch}/{}/native/v1/", manifest.db_name), None)
                .await?;
            anyhow::ensure!(keys.iter().any(|key| key.ends_with(".hadbp")));
            anyhow::ensure!(
                keys.iter().all(|key| !key.ends_with(".ltx")),
                "native layout must never classify HADBP bytes as legacy LTX"
            );
            Ok(())
        }
        .await;
        let _ = child.kill();
        let _ = child.wait();
        migration_result
    }
    .await;

    delete_scratch(&storage, &scratch).await;
    result
}

/// A bucket written by REGISTRY walrust-core 0.7.0 in owned mode
/// (`add_without_snapshot` + autonomous snapshots + compaction) restores
/// row-exact through the current library restore path: `Replicator::restore`
/// to latest and `sync::restore` PITR to the recorded seq/TXID.
#[tokio::test]
async fn format_stability_owned_v0_7_0_bucket_restores_row_exact() -> Result<()> {
    require_s3!("format_stability_owned_v0_7_0_bucket_restores_row_exact");
    let fixture = "owned-v0.7.0";
    let manifest = load_manifest(fixture)?;
    assert_hadbp_objects_decode(fixture, &manifest)?;
    let scratch = unique_scratch_prefix("owned");
    let bucket = test_bucket();
    let endpoint = test_endpoint();
    let storage = walrust::s3_backend_from_env(bucket.clone(), endpoint.as_deref()).await?;

    upload_fixture(&storage, fixture, &manifest, &scratch).await?;

    let prefix = format!("{scratch}/");
    let result = async {
        let temp = tempfile::TempDir::new()?;

        // Restore-to-latest via the library API a real embedder uses.
        let replicator = walrust::walrust_core::Replicator::new(
            storage.clone(),
            &prefix,
            walrust::walrust_core::ReplicationConfig::default(),
        );
        let latest_out = temp.path().join("latest.db");
        let restored_seq = replicator.restore(&manifest.db_name, &latest_out).await?;
        anyhow::ensure!(
            restored_seq.is_some(),
            "owned-v0.7.0: library restore found no data in the uploaded fixture"
        );
        assert_restored_matches(
            "owned-v0.7.0 restore-to-latest",
            &latest_out,
            manifest.latest.row_count,
            &manifest.latest.rows_sha256,
        )?;

        // PITR to the recorded seq/TXID via the library restore entrypoint.
        let pitr_out = temp.path().join("pitr.db");
        walrust::walrust_core::sync::restore(
            storage.clone(),
            &prefix,
            &manifest.db_name,
            &pitr_out,
            Some(&manifest.pitr.txid.to_string()),
        )
        .await
        .context("owned-v0.7.0: PITR restore")?;
        assert_restored_matches(
            "owned-v0.7.0 PITR",
            &pitr_out,
            manifest.pitr.row_count,
            &manifest.pitr.rows_sha256,
        )?;

        // Mid-level PITR: force the leveled planner through each 0.7.0-written
        // L1 merged object (snapshot base at `min-1`, target `max`). The
        // workload that wrote this fixture is INSERT-only with monotonically
        // increasing ids, so every mid-history state must be a strict prefix
        // of the (manifest-anchored) latest rows — a wrong-content restore
        // that somehow passed the chain checksums would still fail here.
        let snapshots = owned_snapshot_seqs(&manifest);
        let latest_rows = read_rows(&latest_out)?;
        let mut mid_level_targets = 0usize;
        for (min, max) in owned_l1_ranges(&manifest) {
            if min == 0 || !snapshots.contains(&(min - 1)) {
                continue;
            }
            mid_level_targets += 1;
            let out = temp.path().join(format!("pitr-l1-{max}.db"));
            walrust::walrust_core::sync::restore(
                storage.clone(),
                &prefix,
                &manifest.db_name,
                &out,
                Some(&max.to_string()),
            )
            .await
            .with_context(|| {
                format!("owned-v0.7.0: mid-level PITR to seq {max} (via L1 {min}-{max})")
            })?;
            assert_integrity_ok(&out).with_context(|| {
                format!("owned-v0.7.0 mid-level PITR seq {max}: integrity_check")
            })?;
            let rows = read_rows(&out)?;
            anyhow::ensure!(
                !rows.is_empty() && rows.len() < latest_rows.len(),
                "owned-v0.7.0 mid-level PITR seq {max}: expected a non-empty strict subset of \
                 latest ({} rows), got {} rows",
                latest_rows.len(),
                rows.len()
            );
            anyhow::ensure!(
                rows == latest_rows[..rows.len()],
                "owned-v0.7.0 mid-level PITR seq {max}: restored rows are not a prefix of the \
                 manifest-anchored latest rows"
            );
        }
        anyhow::ensure!(
            mid_level_targets > 0,
            "owned-v0.7.0: no L1 merged range had a snapshot base at min-1 — the mid-level \
             PITR proof went vacuous; regenerate the fixture or fix the target derivation"
        );
        Ok(())
    }
    .await;

    delete_scratch(&storage, &scratch).await;
    result
}
