//! Format-stability proof (dogfooding item 1): buckets written by the
//! PUBLISHED walrust 0.7.0 artifacts must restore row-exact forever.
//!
//! `tests/fixtures/format-stability/` holds two frozen buckets generated by
//! `generate.sh` from the real crates.io 0.7.0 artifacts (see that script's
//! header): `cli-v0.7.0` (published CLI binary, leveled + pruned,
//! LTX L0 ⟷ HADBP levels seam) and `owned-v0.7.0` (registry walrust-core,
//! owned one-object-per-seq layout + levels). Each test uploads its fixture's
//! objects to a unique scratch prefix on the live S3 endpoint and drives the
//! SAME restore path a real user uses — the CLI binary for the CLI fixture,
//! the library `Replicator::restore()` / `sync::restore()` for the owned one
//! — asserting restore-to-latest and PITR are row-exact against the
//! MANIFEST.json checksums and that `PRAGMA integrity_check` passes.
//!
//! Skip policy (never weaken): these tests skip ONLY when no S3
//! endpoint/credentials are configured, exactly like every other S3-gated
//! test in this file's siblings. When S3 IS configured, a missing or corrupt
//! fixture file is a loud FAILURE — never a skip, never a pass.

use anyhow::{Context, Result};
use hadb_storage::StorageBackend;
use rusqlite::Connection;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

fn test_bucket() -> String {
    std::env::var("TIERED_TEST_BUCKET").unwrap_or_else(|_| "walrust-test-rr-2026".to_string())
}

fn test_endpoint() -> Option<String> {
    std::env::var("AWS_ENDPOINT_URL_S3")
        .or_else(|_| std::env::var("AWS_ENDPOINT_URL"))
        .ok()
}

/// S3-backed tests run only when S3 credentials/an endpoint are configured
/// (same gating as tests/production_e2e.rs — skip ONLY on missing S3 env).
fn s3_test_enabled() -> bool {
    std::env::var("AWS_ENDPOINT_URL_S3").is_ok()
        || std::env::var("AWS_ENDPOINT_URL").is_ok()
        || std::env::var("AWS_ACCESS_KEY_ID").is_ok()
}

macro_rules! require_s3 {
    ($name:literal) => {
        if !s3_test_enabled() {
            eprintln!(concat!(
                "SKIP ",
                $name,
                ": no S3 endpoint/credentials configured (set AWS_ACCESS_KEY_ID or AWS_ENDPOINT_URL_S3)"
            ));
            return Ok(());
        }
    };
}

fn unique_scratch_prefix(fixture: &str) -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("e2e/format-stability/{fixture}-{nanos}")
}

// ── Fixture manifest ────────────────────────────────────────────────────────

#[derive(serde::Deserialize)]
struct Manifest {
    db_name: String,
    latest: RestorePoint,
    pitr: PitrPoint,
    objects: Vec<ObjectEntry>,
}

#[derive(serde::Deserialize)]
struct RestorePoint {
    row_count: u64,
    rows_sha256: String,
}

#[derive(serde::Deserialize)]
struct PitrPoint {
    txid: u64,
    row_count: u64,
    rows_sha256: String,
}

#[derive(serde::Deserialize)]
struct ObjectEntry {
    key: String,
    size: u64,
}

fn fixture_dir(fixture: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/format-stability")
        .join(fixture)
}

/// Load a fixture's manifest. With S3 configured, ANY problem here (missing
/// dir, missing MANIFEST.json, unparseable JSON, empty object list) is a loud
/// test failure — a broken fixture must never look like a pass or a skip.
fn load_manifest(fixture: &str) -> Result<Manifest> {
    let dir = fixture_dir(fixture);
    let manifest_path = dir.join("MANIFEST.json");
    let raw = std::fs::read(&manifest_path).with_context(|| {
        format!(
            "fixture {fixture} is missing or unreadable at {} — \
             regenerate with tests/fixtures/format-stability/generate.sh; \
             this is a FAILURE, not a skip",
            manifest_path.display()
        )
    })?;
    let manifest: Manifest = serde_json::from_slice(&raw)
        .with_context(|| format!("fixture {fixture}: MANIFEST.json is corrupt"))?;
    anyhow::ensure!(
        !manifest.objects.is_empty(),
        "fixture {fixture}: MANIFEST.json lists zero objects"
    );
    anyhow::ensure!(
        manifest.latest.row_count > 0 && manifest.pitr.row_count > 0,
        "fixture {fixture}: manifest row counts must be non-zero"
    );
    Ok(manifest)
}

/// Upload every fixture object to `{scratch_prefix}/{key}`. A missing object
/// file or a size that disagrees with the manifest fails loudly.
async fn upload_fixture(
    storage: &Arc<dyn StorageBackend>,
    fixture: &str,
    manifest: &Manifest,
    scratch_prefix: &str,
) -> Result<()> {
    let objects_dir = fixture_dir(fixture).join("objects");
    for entry in &manifest.objects {
        let path = objects_dir.join(&entry.key);
        let data = std::fs::read(&path).with_context(|| {
            format!(
                "fixture {fixture}: object {} missing at {} — \
                 the checked-in fixture is broken; this is a FAILURE, not a skip",
                entry.key,
                path.display()
            )
        })?;
        anyhow::ensure!(
            data.len() as u64 == entry.size,
            "fixture {fixture}: object {} is {} bytes on disk but MANIFEST.json says {}",
            entry.key,
            data.len(),
            entry.size
        );
        let key = format!("{scratch_prefix}/{}", entry.key);
        storage
            .put(&key, &data)
            .await
            .with_context(|| format!("upload fixture object {key}"))?;
    }
    Ok(())
}

/// Best-effort scratch cleanup: delete everything under the prefix.
async fn delete_scratch(storage: &Arc<dyn StorageBackend>, scratch_prefix: &str) {
    let prefix = format!("{scratch_prefix}/");
    if let Ok(keys) = storage.list(&prefix, None).await {
        for key in keys {
            let _ = storage.delete(&key).await;
        }
    }
}

// ── Row-content checksum (canonical; matches generate.sh) ──────────────────
//
// SHA-256 over the concatenation of "{id}|{value}\n" for
// `SELECT id, value FROM items ORDER BY id`.
fn rows_sha(path: &Path) -> Result<(u64, String)> {
    let conn = Connection::open(path)?;
    let mut stmt = conn.prepare("SELECT id, value FROM items ORDER BY id")?;
    let mut hasher = Sha256::new();
    let mut count = 0u64;
    let rows = stmt.query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, String>(1)?)))?;
    for row in rows {
        let (id, value) = row?;
        hasher.update(format!("{id}|{value}\n"));
        count += 1;
    }
    Ok((count, format!("{:x}", hasher.finalize())))
}

fn assert_integrity_ok(path: &Path) -> Result<()> {
    let conn = Connection::open(path)?;
    let integrity: String = conn.query_row("PRAGMA integrity_check", [], |row| row.get(0))?;
    anyhow::ensure!(integrity == "ok", "integrity_check failed: {integrity}");
    Ok(())
}

fn assert_restored_matches(
    label: &str,
    restored: &Path,
    expected_rows: u64,
    expected_sha: &str,
) -> Result<()> {
    assert_integrity_ok(restored).with_context(|| format!("{label}: integrity_check"))?;
    let (rows, sha) = rows_sha(restored)?;
    anyhow::ensure!(
        rows == expected_rows,
        "{label}: row count mismatch — expected {expected_rows}, restored {rows}"
    );
    anyhow::ensure!(
        sha == expected_sha,
        "{label}: row-content checksum mismatch — expected {expected_sha}, restored {sha}"
    );
    Ok(())
}

// ── CLI restore path (the same binary/path a real CLI user runs) ───────────

fn run_cli_restore(
    name: &str,
    bucket_arg: &str,
    endpoint: Option<&str>,
    restored_path: &Path,
    point_in_time: Option<u64>,
) -> Result<()> {
    let mut restore = Command::new(env!("CARGO_BIN_EXE_walrust"));
    restore
        .arg("restore")
        .arg(name)
        .arg("--output")
        .arg(restored_path)
        .arg("--bucket")
        .arg(bucket_arg);
    if let Some(pit) = point_in_time {
        restore.arg("--point-in-time").arg(pit.to_string());
    }
    if let Some(endpoint) = endpoint {
        restore.arg("--endpoint").arg(endpoint);
    }
    let output = restore.output().context("run walrust restore")?;
    anyhow::ensure!(
        output.status.success(),
        "walrust restore failed (pit={point_in_time:?})\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    Ok(())
}

// ── The proofs ──────────────────────────────────────────────────────────────

/// A bucket written by the PUBLISHED walrust 0.7.0 CLI binary (leveled
/// compaction + a prune boundary, LTX L0 ⟷ HADBP levels seam) restores
/// row-exact through the current CLI restore path: latest + PITR + integrity.
#[tokio::test]
async fn format_stability_cli_v0_7_0_bucket_restores_row_exact() -> Result<()> {
    require_s3!("format_stability_cli_v0_7_0_bucket_restores_row_exact");
    let fixture = "cli-v0.7.0";
    let manifest = load_manifest(fixture)?;
    let scratch = unique_scratch_prefix("cli");
    let bucket = test_bucket();
    let endpoint = test_endpoint();
    let storage = walrust::s3_backend_from_env(bucket.clone(), endpoint.as_deref()).await?;

    upload_fixture(&storage, fixture, &manifest, &scratch).await?;

    let result = (|| -> Result<()> {
        let temp = tempfile::TempDir::new()?;
        let bucket_arg = format!("{bucket}/{scratch}");

        // Restore-to-latest via the real CLI path.
        let latest_out = temp.path().join("latest.db");
        run_cli_restore(
            &manifest.db_name,
            &bucket_arg,
            endpoint.as_deref(),
            &latest_out,
            None,
        )?;
        assert_restored_matches(
            "cli-v0.7.0 restore-to-latest",
            &latest_out,
            manifest.latest.row_count,
            &manifest.latest.rows_sha256,
        )?;

        // PITR to the recorded mid-history TXID via the real CLI path.
        let pitr_out = temp.path().join("pitr.db");
        run_cli_restore(
            &manifest.db_name,
            &bucket_arg,
            endpoint.as_deref(),
            &pitr_out,
            Some(manifest.pitr.txid),
        )?;
        assert_restored_matches(
            "cli-v0.7.0 PITR",
            &pitr_out,
            manifest.pitr.row_count,
            &manifest.pitr.rows_sha256,
        )?;
        Ok(())
    })();

    delete_scratch(&storage, &scratch).await;
    result
}

/// A bucket written by REGISTRY walrust-core 0.7.0 in owned mode
/// (`add_without_snapshot` + autonomous snapshots + compaction) restores
/// row-exact through the current library restore path: `Replicator::restore`
/// to latest and `sync::restore` PITR to the recorded seq/TXID.
#[tokio::test]
async fn format_stability_owned_v0_7_0_bucket_restores_row_exact() -> Result<()> {
    require_s3!("format_stability_owned_v0_7_0_bucket_restores_row_exact");
    let fixture = "owned-v0.7.0";
    let manifest = load_manifest(fixture)?;
    let scratch = unique_scratch_prefix("owned");
    let bucket = test_bucket();
    let endpoint = test_endpoint();
    let storage = walrust::s3_backend_from_env(bucket.clone(), endpoint.as_deref()).await?;

    upload_fixture(&storage, fixture, &manifest, &scratch).await?;

    let prefix = format!("{scratch}/");
    let result = async {
        let temp = tempfile::TempDir::new()?;

        // Restore-to-latest via the library API a real embedder uses.
        let replicator = walrust::walrust_core::Replicator::new(
            storage.clone(),
            &prefix,
            walrust::walrust_core::ReplicationConfig::default(),
        );
        let latest_out = temp.path().join("latest.db");
        let restored_seq = replicator.restore(&manifest.db_name, &latest_out).await?;
        anyhow::ensure!(
            restored_seq.is_some(),
            "owned-v0.7.0: library restore found no data in the uploaded fixture"
        );
        assert_restored_matches(
            "owned-v0.7.0 restore-to-latest",
            &latest_out,
            manifest.latest.row_count,
            &manifest.latest.rows_sha256,
        )?;

        // PITR to the recorded seq/TXID via the library restore entrypoint.
        let pitr_out = temp.path().join("pitr.db");
        walrust::walrust_core::sync::restore(
            storage.clone(),
            &prefix,
            &manifest.db_name,
            &pitr_out,
            Some(&manifest.pitr.txid.to_string()),
        )
        .await
        .context("owned-v0.7.0: PITR restore")?;
        assert_restored_matches(
            "owned-v0.7.0 PITR",
            &pitr_out,
            manifest.pitr.row_count,
            &manifest.pitr.rows_sha256,
        )?;
        Ok(())
    }
    .await;

    delete_scratch(&storage, &scratch).await;
    result
}
